services:
  - type: web
    name: ca-testseries-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node src/index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
